--CRIA A TABELA DE VENDEDORES
CREATE TABLE VENDEDORES (
  ID_VENDEDOR INTEGER NOT NULL,
  NM_VENDEDOR VARCHAR(100),
  CEP VARCHAR(10),
  ENDERECO VARCHAR(100),
  NUMERO   INTEGER,
  BAIRRO VARCHAR(50),
  COMPLEMENTO VARCHAR(20),
  CIDADE VARCHAR(20),
  UF CHAR(2),
  SENHA VARCHAR(10),
  SN_ATIVO    CHAR(1) DEFAULT 'S',
  CONSTRAINT PK_VENDEDORES PRIMARY KEY (ID_VENDEDOR)
);

--CRIA O GENERATOR DO CAMPO ID_VENDEDOR
CREATE SEQUENCE GEN_ID_VENDEDOR;

--CRIA A TRIGGER PARA FAZER O AUTOINCREMENTO NO CAMPO ID_VENDEDOR
CREATE TRIGGER BI_VENDEDORES_ID FOR VENDEDORES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_VENDEDOR IS NULL) THEN
    NEW.ID_VENDEDOR = GEN_ID(GEN_ID_VENDEDOR, 1);
END;


--INSERÇÃO DE MASSA DE DADOS FICTÍCIA
INSERT INTO VENDEDORES (NM_VENDEDOR, CEP, ENDERECO, BAIRRO, COMPLEMENTO, CIDADE, UF, SENHA)
SELECT 'Ana Costa', '01001-000', 'Rua das Flores', 'Centro', 'Ap 101', 'São Paulo', 'SP', '147852' FROM RDB$DATABASE UNION ALL
SELECT 'Carlos Souza', '20040-002', 'Av. Atlântica', 'Copacabana', '', 'Rio de Janeiro', 'RJ', '12345' FROM RDB$DATABASE UNION ALL
SELECT 'Marina Lopes', '30190-000', 'Rua da Bahia', 'Funcionários', 'Sala 3', 'Belo Horizonte', 'MG', '225588' FROM RDB$DATABASE;

