--CRIA A TABELA DE VENDAS
CREATE TABLE VENDAS (
  ID_VENDA INTEGER NOT NULL,
  DT_VENDA TIMESTAMP DEFAULT CURRENT_DATE,
  ID_VENDEDOR INTEGER,
  VL_SUBTOTAL NUMERIC(8,2),
  VL_DESCONTO NUMERIC(8,2),
  VL_ACRESCIMO NUMERIC(8,2),
  VL_TOTAL NUMERIC(8,2),
  PE_DESCONTO NUMERIC(8,4),
  PE_ACRESCIMO NUMERIC(8,4),
  ID_ClIENTE INTEGER,
  
  CONSTRAINT PK_VENDAS PRIMARY KEY (ID_VENDA)
);

--CRIA O GENERATOR DO CAMPO ID_VENDA
CREATE SEQUENCE GEN_ID_VENDA;

--CRIA A TRIGGER PARA FAZER O AUTOINCREMENTO NO CAMPO ID_VENDA
CREATE TRIGGER BI_VENDA_ID FOR VENDAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_VENDA IS NULL) THEN
    NEW.ID_VENDA = GEN_ID(GEN_ID_ID_VENDA, 1);
END;
