--CRIA A TABELA DE ITENS DAS VENDAS
CREATE TABLE ITEMVENDAS (
  ID_ITEM_VENDA INTEGER NOT NULL,
  ID_VENDA INTEGER,
  QT_ITEM INTEGER,
  VL_UNITARIO NUMERIC(8,2),
  VL_TOTAL_ITEM NUMERIC(8,2),
  
  CONSTRAINT PK_ITEMVENDAS PRIMARY KEY (ID_ITEM_VENDA),
  CONSTRAINT FK_ITEMVENDAS_VENDAS FOREIGN KEY (ID_VENDA) REFERENCES VENDAS (ID_VENDA)
);

--CRIA O GENERATOR DO CAMPO ID_ITEM_VENDA
CREATE SEQUENCE GEN_ID_ITEM_VENDA;

--CRIA A TRIGGER PARA FAZER O AUTOINCREMENTO NO CAMPO ID_ITEM_VENDA
CREATE TRIGGER BI_ITEMVENDA_ID FOR ITEMVENDAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_ITEM_VENDA IS NULL) THEN
    NEW.ID_ITEM_VENDA = GEN_ID(GEN_ID_ITEM_VENDA, 1);
END;
