--CRIA A TABELA DE PRODUTOS
CREATE TABLE PRODUTOS (
  ID_PRODUTO  INTEGER NOT NULL,
  NM_PRODUTO  VARCHAR(100),
  DESCRICAO   VARCHAR(100),
  VL_VENDA    NUMERIC(8,2),
  VL_COMPRA   NUMERIC(8,2),
  QT_ESTOQUE  INTEGER,
  SN_ATIVO    CHAR(1) DEFAULT 'S',
  CONSTRAINT PK_PRODUTOS PRIMARY KEY (ID_PRODUTO)
);

--CRIA O GENERATOR DO CAMPO ID_PRODUTO
CREATE SEQUENCE GEN_ID_PRODUTOS;

--CRIA A TRIGGER PARA FAZER O AUTOINCREMENTO NO CAMPO ID_PRODUTO
CREATE TRIGGER BI_PRODUTOS_ID
BEFORE INSERT ON PRODUTOS
AS
BEGIN
  IF (NEW.ID_PRODUTO IS NULL) THEN
    NEW.ID_PRODUTO = NEXT VALUE FOR GEN_ID_PRODUTOS;
END

--INSERÇÃO DE MASSA DE DADOS FICTÍCIA
INSERT INTO PRODUTOS (NM_PRODUTO, DESCRICAO, VL_VENDA, VL_COMPRA, QT_ESTOQUE) 
SELECT 'ÁGUA MINERAL 500ML', 'GARRAFA DE ÁGUA SEM GÁS', 3.50, 1.20, 50            FROM RDB$DATABASE UNION ALL
SELECT 'REFRIGERANTE LATA 350ML', 'COCA-COLA, PEPSI OU SIMILAR', 5.00, 2.50, 60   FROM RDB$DATABASE UNION ALL
SELECT 'CERVEJA LATA 350ML', 'CERVEJA PILSEN EM LATA', 5.50, 2.90, 80             FROM RDB$DATABASE UNION ALL
SELECT 'CAFÉ EXPRESSO', 'CAFÉ PRONTO NA GARRAFINHA', 4.50, 2.00, 30               FROM RDB$DATABASE UNION ALL
SELECT 'CHOCOLATE BARRA 100G', 'BARRA DE CHOCOLATE AO LEITE', 6.00, 3.20, 40      FROM RDB$DATABASE UNION ALL
SELECT 'BALA DE MENTA', 'PACOTE COM 50G DE BALA DE MENTA', 2.00, 0.80, 70         FROM RDB$DATABASE UNION ALL
SELECT 'CHICLETE', 'CHICLETE COM SABOR MORANGO', 1.50, 0.60, 100                  FROM RDB$DATABASE UNION ALL
SELECT 'BISCOITO RECHEADO', 'BISCOITO SABOR CHOCOLATE', 3.00, 1.20, 45            FROM RDB$DATABASE UNION ALL
SELECT 'PÃO DE QUEIJO', 'PACOTE COM PÃO DE QUEIJO CONGELADO', 10.00, 5.00, 20     FROM RDB$DATABASE UNION ALL
SELECT 'SALGADINHO 100G', 'SALGADINHO SABOR QUEIJO', 4.50, 2.10, 35               FROM RDB$DATABASE UNION ALL
SELECT 'ÁGUA COM GÁS 500ML', 'GARRAFA DE ÁGUA COM GÁS', 3.80, 1.50, 30            FROM RDB$DATABASE UNION ALL
SELECT 'ENERGÉTICO LATA 250ML', 'BEBIDA ENERGÉTICA EM LATA', 8.00, 4.20, 25       FROM RDB$DATABASE UNION ALL
SELECT 'SUCO NATURAL 300ML', 'SUCO DE FRUTA PRONTO PARA BEBER', 6.50, 3.00, 25    FROM RDB$DATABASE UNION ALL
SELECT 'SANDUÍCHE NATURAL', 'SANDUÍCHE DE FRANGO COM SALADA', 7.00, 3.50, 15      FROM RDB$DATABASE UNION ALL
SELECT 'BARRA DE CEREAL', 'BARRA DE CEREAL SABOR BANANA', 2.50, 1.10, 40          FROM RDB$DATABASE UNION ALL
SELECT 'PIPOCA DE MICRO-ONDAS', 'SABOR MANTEIGA', 5.50, 2.70, 20                  FROM RDB$DATABASE UNION ALL
SELECT 'LEITE LONGA VIDA 1L', 'CAIXA DE LEITE INTEGRAL', 6.00, 3.10, 35           FROM RDB$DATABASE UNION ALL
SELECT 'IOGURTE 170G', 'IOGURTE COM POLPA DE FRUTA', 3.00, 1.50, 30               FROM RDB$DATABASE UNION ALL
SELECT 'BANDEJA DE FRIOS', 'PRESUNTO E QUEIJO FATIADO', 12.00, 6.00, 10           FROM RDB$DATABASE UNION ALL
SELECT 'BOLINHO INDUSTRIALIZADO', 'BOLINHO RECHEADO', 2.80, 1.30, 40              FROM RDB$DATABASE UNION ALL
SELECT 'GUARDANAPO DE PAPEL', 'PACOTE COM 50 UNIDADES', 4.00, 2.00, 20            FROM RDB$DATABASE UNION ALL
SELECT 'SABONETE 90G', 'SABONETE PERFUMADO', 3.20, 1.50, 30                       FROM RDB$DATABASE UNION ALL
SELECT 'ESCOVA DE DENTE', 'ESCOVA COM CERDAS MACIAS', 4.50, 2.00, 25              FROM RDB$DATABASE UNION ALL
SELECT 'PASTA DE DENTE 90G', 'PASTA COM FLÚOR', 5.00, 2.40, 30                    FROM RDB$DATABASE UNION ALL
SELECT 'DESODORANTE SPRAY', 'DESODORANTE ANTITRANSPIRANTE', 10.00, 5.00, 15       FROM RDB$DATABASE UNION ALL
SELECT 'PAPEL HIGIÊNICO', 'PACOTE COM 4 ROLOS', 8.00, 3.90, 20                    FROM RDB$DATABASE UNION ALL
SELECT 'ISQUEIRO', 'ISQUEIRO RECARREGÁVEL', 2.50, 1.20, 40                        FROM RDB$DATABASE UNION ALL
SELECT 'PILHAS AA 2 UN', 'PILHAS ALCALINAS', 6.00, 3.00, 25                       FROM RDB$DATABASE UNION ALL
SELECT 'CADERNO PEQUENO', 'CADERNO DE ANOTAÇÕES', 8.00, 4.00, 15                  FROM RDB$DATABASE UNION ALL
SELECT 'CANETA ESFEROGRÁFICA', 'COR AZUL', 1.50, 0.70, 50                         FROM RDB$DATABASE UNION ALL
SELECT 'ÁGUA MINERAL 1L', 'GARRAFA DE ÁGUA SEM GÁS 1L', 4.50, 1.80, 40            FROM RDB$DATABASE UNION ALL
SELECT 'REFRIGERANTE 2L', 'REFRIGERANTE DE 2 LITROS', 8.50, 4.20, 20              FROM RDB$DATABASE UNION ALL
SELECT 'CERVEJA LONG NECK', 'GARRAFA 355ML', 6.00, 3.00, 50                       FROM RDB$DATABASE UNION ALL
SELECT 'CHOCOLATE AMARGO', 'BARRA DE CHOCOLATE 70%', 6.50, 3.30, 30               FROM RDB$DATABASE UNION ALL
SELECT 'BISCOITO SALGADO', 'BISCOITO SABOR CEBOLA', 3.50, 1.60, 35                FROM RDB$DATABASE UNION ALL
SELECT 'PÃO DE FORMA', 'PACOTE DE PÃO INTEGRAL', 7.00, 3.50, 25                   FROM RDB$DATABASE UNION ALL
SELECT 'QUEIJO PRATO', 'FATIADO 150G', 12.00, 6.50, 15                            FROM RDB$DATABASE UNION ALL
SELECT 'PRESUNTO COZIDO', 'FATIADO 150G', 11.00, 5.80, 15                         FROM RDB$DATABASE UNION ALL
SELECT 'PICOLÉ', 'PICOLÉ DE FRUTA', 4.00, 2.00, 20                                FROM RDB$DATABASE UNION ALL
SELECT 'SORVETE POTE 1L', 'SORVETE DE CREME', 15.00, 8.00, 10                     FROM RDB$DATABASE UNION ALL
SELECT 'ÁLCOOL EM GEL 70%', 'FRASCO 100ML', 5.00, 2.50, 20                        FROM RDB$DATABASE UNION ALL
SELECT 'MÁSCARA DESCARTÁVEL', 'PACOTE COM 5 UNIDADES', 6.00, 3.00, 30             FROM RDB$DATABASE UNION ALL
SELECT 'LUVAS DE LÁTEX', 'PAR DE LUVAS', 3.00, 1.50, 30                           FROM RDB$DATABASE UNION ALL
SELECT 'SUCO EM CAIXA 1L', 'SUCO DE UVA', 7.00, 3.50, 25                          FROM RDB$DATABASE UNION ALL
SELECT 'CHÁ GELADO 500ML', 'CHÁ DE LIMÃO', 5.00, 2.50, 20                         FROM RDB$DATABASE UNION ALL
SELECT 'ACHOCOLATADO 200ML', 'PRONTO PARA BEBER', 3.50, 1.70, 30                  FROM RDB$DATABASE UNION ALL
SELECT 'LEITE CONDENSADO', 'LATA 395G', 6.00, 3.00, 20                            FROM RDB$DATABASE UNION ALL
SELECT 'CREME DE LEITE', 'CAIXINHA 200G', 4.00, 2.00, 20                          FROM RDB$DATABASE UNION ALL
SELECT 'FARINHA DE TRIGO 1KG', 'FARINHA TIPO 1', 5.50, 2.80, 25                   FROM RDB$DATABASE UNION ALL
SELECT 'AÇÚCAR REFINADO 1KG', 'PACOTE 1KG', 4.50, 2.10, 25                        FROM RDB$DATABASE UNION ALL
SELECT 'SAL DE COZINHA 1KG', 'PACOTE 1KG', 3.00, 1.50, 25                         FROM RDB$DATABASE UNION ALL
SELECT 'ÓLEO DE SOJA 900ML', 'GARRAFA DE ÓLEO', 7.00, 3.80, 20                    FROM RDB$DATABASE UNION ALL
SELECT 'MACARRÃO ESPAGUETE', 'PACOTE 500G', 4.00, 2.00, 25                        FROM RDB$DATABASE UNION ALL
SELECT 'MOLHO DE TOMATE', 'SACHÊ 340G', 3.50, 1.80, 30                            FROM RDB$DATABASE UNION ALL
SELECT 'FEIJÃO CARIOCA 1KG', 'PACOTE 1KG', 7.50, 4.00, 20                         FROM RDB$DATABASE UNION ALL
SELECT 'ARROZ TIPO 1 5KG', 'PACOTE 5KG', 25.00, 15.00, 15                         FROM RDB$DATABASE UNION ALL
SELECT 'CEREAL MATINAL', 'CAIXA 300G', 10.00, 5.00, 15                            FROM RDB$DATABASE UNION ALL
SELECT 'GRANOLA 250G', 'PACOTE COM GRANOLA', 9.00, 4.50, 15                       FROM RDB$DATABASE UNION ALL
SELECT 'PAPEL ALUMÍNIO', 'ROLO 7,5M', 6.00, 3.00, 10                              FROM RDB$DATABASE UNION ALL
SELECT 'DETERGENTE 500ML', 'DETERGENTE LÍQUIDO', 2.50, 1.20, 20                   FROM RDB$DATABASE UNION ALL
SELECT 'ESPONJA MULTIUSO', 'PACOTE COM 3 UNIDADES', 4.00, 2.00, 20                FROM RDB$DATABASE UNION ALL
SELECT 'SABÃO EM PÓ 1KG', 'PARA ROUPAS', 10.00, 5.50, 15                          FROM RDB$DATABASE UNION ALL
SELECT 'AMACIANTE 2L', 'AMACIANTE DE ROUPAS', 12.00, 6.00, 10                     FROM RDB$DATABASE UNION ALL
SELECT 'DESINFETANTE 500ML', 'PARA LIMPEZA GERAL', 4.50, 2.30, 20                 FROM RDB$DATABASE UNION ALL
SELECT 'LÂMPADA LED 9W', 'BRANCA FRIA', 7.00, 3.50, 10                            FROM RDB$DATABASE UNION ALL
SELECT 'CABO USB', 'TIPO C', 12.00, 6.00, 10                                      FROM RDB$DATABASE UNION ALL
SELECT 'CARREGADOR VEICULAR', '2 ENTRADAS USB', 20.00, 10.00, 5                   FROM RDB$DATABASE UNION ALL
SELECT 'ADAPTADOR TOMADA', 'UNIVERSAL', 8.00, 4.00, 10                            FROM RDB$DATABASE UNION ALL
SELECT 'CAIXA DE FÓSFORO', 'CONTÉM 10 UNIDADES', 2.00, 1.00, 30                   FROM RDB$DATABASE;