CREATE OR ALTER PROCEDURE ST_GRAVAITENSVENDA (
    ID_VENDA INTEGER,
	ID_PRODUTO INTEGER,
    QT_ITEM INTEGER,
    VL_UNITARIO NUMERIC(8,2),
    VL_TOTAL_ITEM NUMERIC(8,2)
)
AS
BEGIN
  INSERT INTO ITEMVENDAS (
    ID_VENDA,
	ID_PRODUTO,
    QT_ITEM,
    VL_UNITARIO,
    VL_TOTAL_ITEM
  )
  VALUES (
    :ID_VENDA,
	:ID_PRODUTO,
    :QT_ITEM,
    :VL_UNITARIO,
    :VL_TOTAL_ITEM
  );
END