--CRIA A TABELA DE CLIENTES
CREATE TABLE CLIENTES (
  ID_CLIENTE INTEGER NOT NULL,
  NM_CLIENTE VARCHAR(100),
  CEP VARCHAR(10),
  ENDERECO VARCHAR(100),
  NUMERO   INTEGER,
  BAIRRO VARCHAR(50),
  COMPLEMENTO VARCHAR(20),
  CIDADE VARCHAR(20),
  UF CHAR(2),
  SN_ATIVO    CHAR(1) DEFAULT 'S',
  
  CONSTRAINT PK_CLIENTES PRIMARY KEY (ID_CLIENTE)
);

--CRIA O GENERATOR DO CAMPO ID_CLIENTE
CREATE SEQUENCE GEN_ID_CLIENTE;

--CRIA A TRIGGER PARA FAZER O AUTOINCREMENTO NO CAMPO ID_CLIENTE
CREATE TRIGGER BI_CLIENTES_ID FOR CLIENTES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_CLIENTE IS NULL) THEN
    NEW.ID_CLIENTE = GEN_ID(GEN_IID_CLIENTE, 1);
END;


--INSERÇÃO DE MASSA DE DADOS FICTÍCIA
INSERT INTO CLIENTES (NM_CLIENTE, CEP, ENDERECO, BAIRRO, COMPLEMENTO, CIDADE, UF)
SELECT 'Ana Costa', '01001-000', 'Rua das Flores', 'Centro', 'Ap 101', 'São Paulo', 'SP' FROM RDB$DATABASE UNION ALL
SELECT 'Carlos Souza', '20040-002', 'Av. Atlântica', 'Copacabana', '', 'Rio de Janeiro', 'RJ' FROM RDB$DATABASE UNION ALL
SELECT 'Marina Lopes', '30190-000', 'Rua da Bahia', 'Funcionários', 'Sala 3', 'Belo Horizonte', 'MG' FROM RDB$DATABASE;

